### ISSUE TITLE
Transition Dipoles

### ISSUE THREAD

**Issue by pwborthwick** [pwborthwick/projects#1]
If you have a moment please could you help me with this @jjgoings. It follows on from our discussions on RTHF and in particular on oscillator strength and transition dipole. As I mentioned in my last e-mail getting transition dipoles from the addendum to your blog article 'TDHF + CIS in Python' wasn't entirely clear. I did my own calculations and followed steps that you seem to have trodden earlier re. biorthogonalization - I saw your question to stackexchange and the subsequent blog article. So

Firstly, as you remind us the dipoles are in the atomic basis and our excitations/de-excitations will be in a molecular spin basis so convert dipole to molecular basis with right shape
         &#956;<sub>(mo) ia</sub> = c<sup>p</sup><sub>i</sub> &#956;<sub>(ao) pq</sub> c<sup>q</sup><sub>a</sub>
that is 

         dot(c[:, nocc].T , dot(mu[:,:], c[:,nVir]))
To have a specific example let's use H<sub>2</sub> in 3-21g basis. Then &#956; and c will be [4,4], nocc = 1 (doubly occupied) and nvir = 3    =>  &#956;<sub>(mo)</sub> will have shape [1,4][4,4][4,3] ie [1,3]
I can check this with a [psi4 notebook](https://tinyurl.com/tddft-psicon2020), the z-dipole component calculated from 
my code is....  [  1.019407,    4.218847e-15,   0.161860]
psi4.............. [ 1.019407, -7.426375e-16,    0.161860]
OK so far.

Since we are discussing TDDFT/TDHF I used code I have for TDHF-RPA. Building the response eigenvalue problem (A-B).(A+B) |X+Y> = &#969;<sup>2</sup> |X+Y> and solving as

        w , vl, vr = scipy.linalg.eig(rpaH, left=True, right=True)

I get (unsorted) eigenvectors (brought to eV and square rooted)
[*46.40582513* **15.49943826** 39.78702658 39.78702658  *31.97665656* 9.83612223  9.83612223 39.78702658
  9.83612223 25.72073352 25.72073352 25.72073352]
I've marked in bold the lowest singlet state which compares to your Gaussian16 value of 15.4997 and psi4 value of (0.5696022808446858 * 27.211) = 15.499447. You can see the second and third singlets from your Gaussian calculation 31.9771 and 46.4065 in italics above. *I find running psi4 with 'nocom', 'noreorient', 'scf_type = direct' and 'puream = False' gives really close agreement with mmd and my code (which is also McMurchie-Davidson based)*

OK let's assume the RPA is correct  and scipy has also given us correct left and right eigenvectors. So next is the biorthogonalization. You define matrices L,R as biorthogonal if <L,R> = I, <> is inner product. Inner product for matrices is defined by einsum(ij,kj->ik) and this is how it is calculated by np.inner. This is also equivalent to np.dot(L, R.T) which is perhaps closer to how we usually think of orthogonal matrices. So using one of

          m = np.inner(vl, vr)   ,    np.dot(vl, vr.T)  ,   np.einsum('ij,kj->ik', vl,vr)
          # do an LU decomposition
          ml, mu = scipy.linalg.lu(m, True)

          lp = np.dot(np.linalg.inv(ml), vl)
          rp = np.dot(vr, np.linalg.inv(mu))

we would hope np.allclose(np.inner(lp, rp), np.eye(12)) would be True but it returns False. 
Anyway we get a vector for the first singlet with 2xoccupiedx2xvirtual entries and we can extract the right alpha eigenvectors as elements [0, 2, 4] which are [7.06459873e-01   5.48775424e-16  -3.02398362e-02] and the psi4 values are  [9.26668084e-01,  5.22863415e-16, -3.96657967e-02]. **For now note that the ratio element 0 : 2 is 23.3619 in both cases**

Psi4 uses this approach to bnormalize the eigenvectors
           inners = np.einsum("ix,ix->x", vr, vl, optimize=True)
           rp = np.einsum("x,ix->ix", 1. / np.sqrt(inners), vr, optimize=True)
           lp = np.einsum("x,ix->ix", 1. / np.sqrt(inners), vl, optimize=True)
this leads to the same rp, lp matrices as in the LU decomposition case. 

The questions are why aren't the left and right biorthogonal vectors very biorthogonal and why are our results and psi4 results different by a scaling factor?

We can use the psi4 results to get the electronic transition dipole (z) as sum(&#956;<sub>(mo)</sub> * excitations) so
[ 1.019407, -7.426375e-16,    0.161860]*[9.26668084e-01,  5.22863415e-16, -3.96657967e-02]*sqrt(2) = 1.326859
and then the oscillator strength as 2/3 * excitation energy [0.569602] * dipole<sub>z</sub><sup>2</sup> = 0.6685 (the oscillator strength from your Gaussian calculation).

We could go on using the left eigenvectors and nabla integral rather than dipole to calculate in the velocity gauge. Also left eigenvectors and angular momentum to get magnetic dipole and rotary stengths. But for now I need to get the right transition dipoles.

Have you any idea why the left and right eigenvectors  are aren't right? All units are au throughout. I'd appreciate some help as I'm sure you've done this before. BTW I was playing with the real-time Pade stuff and looked at using fft.fft from python instead. What happened was that the spectrum was upside-down needing the field to be reversed ie subtracting the field as you thought should be the case. This suggests that perhaps the Pade is responsible for needing to add the field instead? Using pade was much nicer! 

Hope all OK with you.
              Best Peter

Addendum:
We want <L, R> = I, but at present it = M, say
This is equivalent to  L.R<sup>T</sup> = M, do LU decomposition
L.R<sup>T</sup> = M<sub>l</sub>.M<sub>u</sub>   =>  (M<sub>l</sub>)<sup>-1</sup>.L.R<sup>T</sup>.(M<sub>u</sub>)<sup>-1</sup> = I
If L<sup>'</sup> =  (M<sub>l</sub>)<sup>-1</sup>.L   and (R<sup>'</sup>)<sup>T</sup> = R<sup>T</sup>.(M<sub>u</sub>)<sup>-1</sup>  then L<sup>'</sup>.(R<sup>'</sup>)<sup>T</sup> = I and L<sup>'</sup> and R<sup>'</sup> are biorthogonal.
so our left eigenvectors are given by (M<sub>l</sub>)<sup>-1</sup>.L and our right are given by (R<sup>T</sup>.(M<sub>u</sub>)<sup>-1</sup>)<sup>T</sup> = (M<sub>u</sub><sup>T</sup>)<sup>-1</sup>.R

Doing it this way stops any confusion as to whether were using inner or dot products and is clearly different to R<sup>'</sup> derived in the blog. Maybe we have a different definition of biorthogonal matrices? Now doing np.allclose(np.inner(L<sup>;</sup>, R<sup>'</sup>), np.eye(12)) results in True. **The  eigenvectors produced are still wrong though !?**

Addaddendum:
I've started doubting my original code now so I checked my RPA calculation and checked back to your TDHF+CIS blog article. My sources (Crawford and others) give the equation 

A<sub>ia,jb</sub> = f<sub>ab</sub>&#948;<sub>ij</sub> -  f<sub>ij</sub>&#948;<sub>ab</sub> + <aj|ib>
this leads to eg A<sub>01,02</sub> = f<sub>12</sub>&#948;<sub>00</sub> - f<sub>00</sub>&#948;<sub>12</sub> + <10|02> =  f<sub>12</sub> + <10|02>
whereas your code evaluates to (f<sub>11</sub> -  f<sub>00</sub>) * &#948;<sub>00</sub> *  &#948;<sub>12</sub> + <10|02> = <10|02>. ??

**Comment by jjgoings** [comment]
Hi @pwborthwick 
Sorry...been busy and I've had trouble finding this issue page, though I did get the email notification. I'm not totally sure where the problem lies, so it might be useful for me to try and quick code up a TDHF/CIS in `mmd`. One thing you could try is to do the Hermitian variant of TDHF (Eq 16 of attached paper) and then you can skip the biorthogonalization directly, e.g. solve

<img src="https://render.githubusercontent.com/render/math?math=\left(\mathbf{A} - \mathbf{B}\right)^{1/2}\left(\mathbf{A} %2B \mathbf{B}\right)\left(\mathbf{A} - \mathbf{B}\right)^{1/2} \mathbf{T} = \omega^2 \mathbf{T}">

where

<img src="https://render.githubusercontent.com/render/math?math=\mathbf{T} = \left(\mathbf{A} - \mathbf{B}\right)^{-1/2} \vert \mathbf{X} %2B \mathbf{Y}\rangle">

[J. Chem. Phys. 1998, 109, 8218.pdf](https://github.com/pwborthwick/ToDo/files/5884068/J.Chem.Phys.1998.109.8218.pdf)

It might not fix anything, but sometimes solving things another way can shed light on the important issues. I'll have to double check the blog post, but if there is an error, thanks for letting me know!

**Comment by pwborthwick** [comment]
Hi @jjgoings ,
   Thanks for your reply. Firstly I've checked my implementation of RPA against the results for water given by Crawford - [https://github.com/CrawfordGroup/ProgrammingProjects/tree/master/Project%2312](url). I'm getting the same Hamiltonian and eigenvalues for RPA method I, so I assume my calculation of A and B is OK. For RPA II I'm getting the right eigenvalues too. I've implemented your 'TDHF+CIS' blog algorithm for A and B and that fails to reproduce the right eigenvalues and Hamiltonian. I'll put the code for the test below

    ia = 0
    for i in range(0, nElectrons):
        for a in range(nElectrons, spinOrbitals):

            jb = 0
            for j in range(0, nElectrons):
                for b in range(nElectrons, spinOrbitals):

    #Josh's algorithm--------------------------------------------------------------------------------------
                    A[ia,jb] = (fockMOspin[a,a] - fockMOspin[i,i]) * (i==j) * (a==b) * eriMOspin[a,j,i,b]
                    B[ia,jb] = eriMOspin[a,b,i,j]
    #Original code-----------------------------------------------------------------------------------------
    #               if (i == j):
    #                   A[ia,jb] += fockMOspin[a,b]
    #               if (a == b):
    #                   A[ia,jb] -= fockMOspin[i,j]

    #               A[ia,jb] += eriMOspin[a,j,i,b]
    #               B[ia,jb] += eriMOspin[a,b,i,j]

                    jb += 1
             ia += 1

    rpaH = np.block([[A, B], [-B, -A]])

I see your implementation is from the paper you referenced equations 10 and 11 and mine is from Crawford's project 12 referenced above. The equations seem quite different Crawford allowing many more terms than equation 10. The Psi4 Jupyter notebook gives 𝐴<sub>𝑎𝑖𝑏𝑗</sub>=𝛿<sub>𝑖𝑗</sub>𝑓<sub>𝑎𝑏</sub>−𝛿<sub>𝑎𝑏</sub>𝑓<sub>𝑖𝑗</sub>+(𝑎𝑖|𝑗𝑏)−𝛾(𝑎𝑏|𝑗𝑖)+𝑤xc; - the two versions - Crawford/Psi4 v equation 10 - cannot as far as I can see give equivalent descriptions. Anyway when you code this up we'll see what results you get.

I've tried the Hermitian version (thanks for the paper) I think psi4 essentially uses that form, but I still don't get the right answer. The ratio between the alpha eigenvalues is (annoyingly) still the same as the (correct) psi4 ones from the jupyter notebook I mentioned, although the values themselves are different. But once you've solved for T and then for |X+Y> the resulting |X+Y> are no longer normal, normalise and you get back the alpha eigenvalues I originally got from the non-Hermitian case!!! I've just got this feeling I'm missing something that should be blindingly obvious.

As for the biorthogonalisation, I think the answer you received from your original enquiry may not be wholly correct. The responder has assumed (as far as I can see) that all matrix multiplication is standard 'dot' product. Therefore he has assumed that the problem you stated as <L,R> was L.R, he has then solved L.R = I leading to matrices that form a A, A<sup>-1</sup> pair under dot multiplication. That's not really what you wanted was it? I think the solution I gave in my earlier post does work though. As an example

    import numpy as np
    from scipy.linalg import eig, lu

    A = np.array([[2,4], [-1,3]])
    w, l, r = eig(A, left=True, right=True)

    #blog algorithm (as interpreted)
    tm= np.inner(l,r)
    ml, mr = lu(m, True)
    vl = np.dot(np.linalg.inv(ml), l)
    vr = np.dot(r, np.linalg.inv(mu))
    print(np.inner(vl, vr))
    [ 2.366666 + 5.527503e-18j            2.958333 - 9.198335e-01j
     -2.776664e-17 + 6.616346e-01j     6.796875e-01 + 8.270433e-02j  ]

     #my algorithm
     vr = np.dot(np.linalg.inv(mu.T), r)
     print(np.inner(vl,vr))
     [ 1.000000 + 0.000000j      6.969541e-17 - 2.513052e-17j
      -1.060168 e-17 - 7.500625e-18j   1.000000 - 3.770229e-18j]

     #blog algorithm (as written)
     tm = np.dot(l,r)
     ml, mr = lu(m, True)
     vl = np.dot(np.linalg.inv(ml), l)
     vr = np.dot(r, np.linalg.inv(mu))
     print(np.dot(vl, vr))
     [ 1.000000 + 2.388792e-17j     -3.454554e-16 + 1.734722e-16j
       3.373243e-17 +~ 6.466016e-18j  1.000000 - 1,475775e-17j]

    

On another matter I decided to do a clean installation of mmd. It now has a dependency on bitstring which is not mentioned yet in the readme (I expect you just haven't got round to it yet). Also 17 of 20 nosetests are failing with 'ImportError: No module named onee' but this could just be the installation on my machine but in that case don't know why it picks on that module to complain about. A test will run if I move it to the main McMurchie-Davidson-master directory so I guess its a path problem.

On a brighter note I've had my covid 19 jab :) 
   Best Peter

**Comment by jjgoings** [comment]
Hi @pwborthwick 

It looks like a "+" was accidentally replaced with a "*". Note that

```
#Josh's algorithm--------------------------------------------------------------------------------------
                A[ia,jb] = (fockMOspin[a,a] - fockMOspin[i,i]) * (i==j) * (a==b) * eriMOspin[a,j,i,b]
```

should be 

```
#Josh's algorithm--------------------------------------------------------------------------------------
                A[ia,jb] = (fockMOspin[a,a] - fockMOspin[i,i]) * (i==j) * (a==b) + eriMOspin[a,j,i,b]
```

otherwise the A matrix is wrongly diagonal. (This took me far too long to notice.)

With this change, both methods agree as well as agree with the tests for water/3-21G in Gaussian. I'll clean up and add my tests soon.

BTW, try installing `mmd` as a local install with

```
python setup.py build_ext --inplace install --user
```

Then you don't have to always be in the main directory to run scripts. Sounds like there were issues with `cython`. You need to rebuild the integral package (`onee` and `twoe`) with `cython` in order to work. This should be handled automatically by the setup command above (`cython` is handled with the `build_ext --inplace`).

I will explain more another time, but I've recently added in some routines to evaluate Slater-Condon rules between arbitrary Slater determinants. We represent the determinants as bitstrings (hence the `bitstring` module, which is convenient at the moment). Some of the new tests that presumably fail due to `bitstring` dependency are the FCI and CISD tests. They should pass otherwise. Looking at the individual test files (e.g. `test017.py` etc.) might be enlightening in the absence of me updating documentation...TBD...

Happy you got your jab!

**Comment by pwborthwick** [comment]
Hi @jjgoings ,
   I can't believe I did that! I've been staring at that line for ages, you know it should be '+' and thats all you see. I'm sorry for wasting your time on that. Happy that the versions are the same now.
Thanks the 'install --user' is a great help. Can't get nosetests to work still - it's not onee specifically it just happens to be the first module called from Molecule. Running the tests as python command works so don't worry about it  as it's not crucial.
 I've found the paper with the bit string handling of excited determinants and have added it to my list of things to read.
Back to the transition dipoles now :(
     Peter

Just found your implementation of TDHF. Running it for H<sub>2</sub>...

    E(SCF)    =  -1.122940218532 in 3 iterations
    Time-dependent Hartree-Fock (TDHF)
    ------------------------------
    Algorithm:         reduced
    Matrix shape:      12
    2 * nOcc * nVirt:  24
    TDHF state  1 (eV):       9.8709
    TDHF state  2 (eV):       9.8709
    TDHF state  3 (eV):       9.8709
    TDHF state  4 (eV):      15.5336
    TDHF state  5 (eV):      25.7916
    TDHF state  6 (eV):      25.7916
    TDHF state  7 (eV):      25.7916
    TDHF state  8 (eV):      32.0479
    TDHF state  9 (eV):      39.8302
    TDHF state 10 (eV):      39.8302

The Gaussian 16 values you got were

    Excited State   1:      Singlet-SGU   15.4997 eV   79.99 nm  f=0.6685  <S**2>=0.000
       1 ->  2         0.70960
     This state for optimization and/or second-order correction.
     Total Energy, E(TD-HF/TD-DFT) = -0.553338323725
     Copying the excited state density for this state as the 1-particle RhoCI density.

     Excited State   2:      Singlet-SGG   31.9771 eV   38.77 nm  f=0.0000  <S**2>=0.000
       1 ->  3         0.70794

     Excited State   3:      Singlet-SGU   46.4065 eV   26.72 nm  f=0.0381  <S**2>=0.000
       1 ->  4         0.70804

running my code I get (with same geometry and 3-21g throughout) (data is unprocessed but converted to eV)

    -1.122940258837292  in  0.076 s
    [46.40582513+0.j 15.49943826+0.j  9.83612223+0.j  9.83612223+0.j
     39.78702658+0.j 25.72073352+0.j 31.97665656+0.j  9.83612223+0.j
     39.78702658+0.j 39.78702658+0.j 25.72073352+0.j 25.72073352+0.j]

Your A and B are already different from mine. So difference is above that in the code. Our SCF energies are the same'ish 
**OK I've found out why the values are a bit off. It's down to the DIIS convergence again. With DIIS switched on the solution is not properly converged (small molecule/small basis set), switch DIIS off and values agree well with Gaussian 16.**
